name: Update docs on pushes to master
"on":
  push:
    branches:
      - master
jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm --prefix ./docs ci ./docs
      - run: npm run build --prefix ./docs -- --prefix-paths
      - uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: docs/public/
          GH_PAT: ${{ secrets.OCTOKITBOT_PAT }}
